# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Project-page : A graph construction study for graph-based semi-supervised learning' 
email: sumedhyadav.iitkgp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Case study keeping unstructured text data in mind. This project falls under the category of graph-based machine learning and big data.
baseurl: "/graph_heuristic" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

author: Sumedh Yadav, Gautam Kumar
# trial
# background-image: url('/assets/img/home-bg.svg')

# mathis details
author2: Shivam Kumar

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# New description
# This method focuses on reducing training time of machine learning algorithms. It falls under the category of distributed machine learning and algorithms for Big Data.
  
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
# This method focuses on reducing training time of machine learning algorithms. 
#   It falls under the category of distributed machine learning and algorithms for Big Data.